### ISSUE TITLE
Why copy the complete extension?

### ISSUE THREAD

**Issue by lochmueller** [checkitsedo/checkitcalendarize#1]
Hey...

qhy you copy (and not fork) the complete extension and rename all namespaces?
This handling make merges and pull requests impossible and I understand not the usecase :-/ 
Sorry for my questions, but I try to streamline all the work arround the extension...

Regards,
Tim

**Comment by checkitsedo** [comment]
Hallo Tim

Das Warum kann ich dir kurz erklären: Ich versuche zu lernen, wie saubere Extensions programmiert werden und wie ich bei einer Extension weitere Funktionen einfügen kann. Diese ganze Thematik ist für mich ziemlich neu, und so probiere ich verschiedenes aus. Auch habe ich versucht, mir einen GIT-Workflow zu machen, aber da liegt noch viel Arbeit vor mir... Es leuchtet mir ein, dass mein Handling Merges und Pull Requests verunmöglichen; aber wie gesagt: es ist nirgendwo im Einsatz...
Damit du etwas von deiner Liste streichen kannst, lösche ich dieses Repository in den nächsten Tagen. Wenn es schneller gehen soll, einfach kurz antworten.

Ich hoffe, das ist in deinem Sinne und nichts für ungut (wegen des Aufwandes, den du wegen mir hattest).

Beste Grüsse
Dominik

**Comment by lochmueller** [comment]
Hey Dominik,

Aufwand hatte ich keinen. Vielen Dank für dein Feedback. Hatte nur mal die Commits überflogen ob etwas "brauchbares" dabei ist, dann aber gesehen, dass ziemlich viel nur Namespace Anpassungen sind.

Tipps für das nächste mal:
- Benutzer ruhig die "Fork" Funktion. Dadruch sind die Repositories verbunden und es lässt sich leichter Code austauschen (sowohl in meine Richtung als auch in deine Richtung)
- Du brauhcsts das Package nicht umbennen (machen auch gerne viele). Du kannst auch das Package aus deinem Repository mittels compooser installieren ohne den Package Key ändern zu müssen. 
- Im Idealfall einzelne Branches für einzelne Änderungen

Wenn das berücksichtigt wurde, dann kann man coole Ideen gut und schnell übernehmen.

Danke für dein Feedback.

Beste Grüße,
Tim
